spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/flowable
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

management:
  endpoints:
    web:
      exposure:
        include:
          - flowable
          - info
flowable:
  history-level: full
  simpleDbIdGenerator: true
