spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  # Set here configurations for the database connection
  datasource:
    url: jdbc:postgresql://localhost:5432/flowable
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1

#springdoc:
#  packagesToScan: >-
#    com.example,
#    org.flowable
#  pathsToMatch: >-
#    /demo/**,
#    /pm/**,
#    /flowable-rest/**,
#    /process-api/**,
#    /**
#
management:
  endpoints:
    web:
      exposure:
        include:
          - flowable
          - info
flowable:
  history-level: full
  simpleDbIdGenerator: true
